version: "3"

services:

  app:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    image: weblinuxgame/bitmapserv:${SERVICE_VERSION:-v1.0.5}
    container_name: bitMapServ
    hostname: bitMapServ
    volumes:
      - ".docker/etc:/app/etc"
      - ".docker/docs:/app/docs"
      - ".docker/logs:/app/logs:rw"
      - "/etc/localtime:/etc/localtime"
    ports:
    -  "28001:8080"
    restart: always
    networks:
      - bongolive

networks:
  bongolive:
    external: true