version: "3"

services:

  rpc:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    image: weblinuxgame/bitmapserv-rpc:${SERVICE_VERSION:-v1.0.6}
    container_name: bitMapRpcServ
    hostname: bitMapRpcServ
    volumes:
      - ".docker/etc:/app/etc"
      - ".docker/logs:/app/logs:rw"
      - "/etc/localtime:/etc/localtime"
    cpu_count: 2
    mem_reservation: 512m
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512m
    ports:
      - "18002:8080"
    restart: always
    depends_on:
      - "etcd"
    networks:
      - "rpc"

  etcd:
    image: "bitnami/etcd:latest"
    hostname: "etcd"
    environment:
      - "ETCDCTL_API=3"
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379"
    ports:
      - "2379:2379"
      - "2380:2380"
    cpu_count: 2
    mem_reservation: 512m
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512m
    restart: always
    networks:
      - "rpc"

networks:
  rpc:
    driver: bridge
