// Code generated by goctl. DO NOT EDIT.
package types

type SingleRequest struct {
	Date       string `form:"date,optional" desc:"查询日期"`
	Type       int    `form:"type,default=0" desc:"留存类型(0:日期为截止日,1:日期为开始日)"`
	Day        int    `form:"day,range=[1:366]" desc:"第几日留存"`
	Channel    string `form:"channel,optional" desc:"渠道名"`
	Role       string `form:"role,optional" desc:"身份类型"`
	DataSource string `form:"data_source,optional" desc:"数据源"`
}

type MulitRequest struct {
	Date       string `form:"date,optional" desc:"查询日期"`
	Type       int    `form:"type,default=0" desc:"留存类型(0:日期为截止日,1:日期为开始日)"`
	Days       []int  `form:"days," desc:"留存天集合"`
	Channel    string `form:"channel,optional" desc:"渠道名"`
	Role       string `form:"role,optional" desc:"身份类型"`
	DataSource string `form:"data_source,optional" desc:"数据源"`
}

type MulitChannelsRequest struct {
	Date       string   `form:"date,optional" desc:"查询日期"`
	Type       int      `form:"type,default=0" desc:"留存类型(0:日期为截止日,1:日期为开始日)"`
	Days       []int    `form:"days," desc:"留存天集合"`
	Channels   []string `form:"channels" desc:"渠道名"`
	Role       string   `form:"role,optional" desc:"身份类型"`
	DataSource string   `form:"data_source,optional" desc:"数据源"`
}

type BaseResponse struct {
	Code    int    `json:"code" desc:"业务码"`
	Msg     string `json:"msg" desc:"业务提示"`
	ErrorNo int    `json:"errorNo,optional" desc:"错误码"`
}

type KeeperStruct struct {
	Keep     string `json:"keep" desc:"留存"`
	Name     string `json:"name" desc:"留存描述"`
	Register int    `json:"total" desc:"开始时间注册量"`
	Left     int    `json:"left" desc:"当天留存量"`
}

type ChannelResponse struct {
	Channel string          `json:"channel" desc:"渠道名"`
	Items   []*KeeperStruct `json:"items" desc:"结果集合"`
}

type SingleResponse struct {
	BaseResponse
	Data *KeeperStruct `json:"data" desc:"结果数据"`
}

type MulitResponse struct {
	BaseResponse
	Data []*KeeperStruct `json:"data" desc:"结果集合"`
}

type MulitChannelsResponse struct {
	BaseResponse
	Data []*ChannelResponse `json:"data" desc:"结果集合"`
}
