// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/weblfe/bitmap_service/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/bitmap/userkeeper",
				Handler: BitMapServSingleGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/bitmap/userkeeper",
				Handler: BitMapServSinglePostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/bitmap/userkeepers",
				Handler: BitMapServMultiGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/bitmap/userkeepers",
				Handler: BitMapServMultiPostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/bitmap/channels/userkeepers",
				Handler: BitMapServChannelsMultiGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/bitmap/channels/userkeepers",
				Handler: BitMapServChannelsMultiPostHandler(serverCtx),
			},
		},
	)
}
